controller_list:
  - name: fake_kinova_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - kinova_arm_joint_1
      - kinova_arm_joint_2
      - kinova_arm_joint_3
      - kinova_arm_joint_4
      - kinova_arm_joint_5
      - kinova_arm_joint_6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - kinova_arm_right_finger_bottom_joint
initial:  # Define initial robot poses.
  - group: kinova_arm
    pose: Stand