# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: kinova_arm
  joint_model_group_pose: Stand
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - front_left_wheel
    - front_right_wheel
    - rear_left_wheel
    - rear_right_wheel
    - kinova_arm_joint_1
    - kinova_arm_joint_2
    - kinova_arm_joint_3
    - kinova_arm_joint_4
    - kinova_arm_joint_5
    - kinova_arm_joint_6
    - kinova_arm_right_finger_bottom_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: kinova_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - kinova_arm_joint_1
      - kinova_arm_joint_2
      - kinova_arm_joint_3
      - kinova_arm_joint_4
      - kinova_arm_joint_5
      - kinova_arm_joint_6
kinova_gripper_contoller:
  type: position_controllers/GripperActionController
  joints:
    kinova_arm_right_finger_bottom_joint
  gains:
    kinova_arm_right_finger_bottom_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1