kinova_arm_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

kinova_arm_gen3_lite_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - kinova_arm_joint_1
    - kinova_arm_joint_2
    - kinova_arm_joint_3
    - kinova_arm_joint_4
    - kinova_arm_joint_5
    - kinova_arm_joint_6
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.5
  stop_trajectory_duration: 1.0
  state_publish_rate: 25
  action_monitor_rate: 25
  gains:
    kinova_arm_joint_1:
      { p: 3000.0, i: 0.0, d: 2.0, i_clamp_min: -100.0, i_clamp_max: 100.0 }
    kinova_arm_joint_2:
      { p: 50000.0, i: 0.0, d: 0.0, i_clamp_min: -5.0, i_clamp_max: 5.0 }
    kinova_arm_joint_3:
      { p: 50000.0, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    kinova_arm_joint_4:
      { p: 750.0, i: 0.0, d: 0.2, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    kinova_arm_joint_5:
      { p: 5000.0, i: 0.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0 }
    kinova_arm_joint_6:
      { p: 100.0, i: 0.0, d: 0.0, i_clamp_min: -0.1, i_clamp_max: 0.1 }

kinova_arm_joint_1_position_controller:
  joint: kinova_arm_joint_1
  pid:
    p: 3000.0
    i: 0.0
    d: 2.0
  type: effort_controllers/JointPositionController

kinova_arm_joint_2_position_controller:
  joint: kinova_arm_joint_2
  pid:
    p: 50000.0
    i: 0.0
    d: 0.0
  type: effort_controllers/JointPositionController

kinova_arm_joint_3_position_controller:
  joint: kinova_arm_joint_3
  pid:
    p: 50000.0
    i: 0.0
    d: 0.0
  type: effort_controllers/JointPositionController

kinova_arm_joint_4_position_controller:
  joint: kinova_arm_joint_4
  pid:
    p: 750.0
    i: 0.0
    d: 0.2
  type: effort_controllers/JointPositionController

kinova_arm_joint_5_position_controller:
  joint: kinova_arm_joint_5
  pid:
    p: 5000.0
    i: 0.0
    d: 1.0
  type: effort_controllers/JointPositionController

kinova_arm_joint_6_position_controller:
  joint: kinova_arm_joint_6
  pid:
    p: 100.0
    i: 0.0
    d: 0.0
  type: effort_controllers/JointPositionController

kinova_arm_gen3_lite_2f_gripper_controller:
  type: "position_controllers/GripperActionController"
  joint: kinova_arm_right_finger_bottom_joint
  action_monitor_rate: 100

gazebo_ros_control:
  pid_gains:
    kinova_arm_right_finger_bottom_joint: { p: 10.0, i: 0.0, d: 0.0 }
    kinova_arm_right_finger_tip_joint: { p: 1.0, i: 0.0, d: 0.0 }
    kinova_arm_left_finger_bottom_joint: { p: 10.0, i: 0.0, d: 0.0 }
    kinova_arm_left_finger_tip_joint: { p: 1.0, i: 0.0, d: 0.0 }
